name: Deploy to Development

on:
  push:
    branches: [ develop ]
    paths:
      - 'src/**'
      - 'functions/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'firebase.json'
      - '.firebaserc'

jobs:
  deploy-dev:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm run test:unit
      
      - name: Build project
        run: npm run build
      
      - name: Set environment variables for Firebase
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}" >> $GITHUB_ENV
      
      - name: Set Firebase project
        run: npx firebase use db888-dev
      
      - name: Set Firebase Functions configuration
        run: |
          npx firebase functions:config:set \
            database.host="$DB_HOST" \
            database.user="$DB_USER" \
            database.password="$DB_PASSWORD" \
            database.name="$DB_NAME" \
            environment.name="development"
      
      - name: Deploy Firebase Functions
        run: npx firebase deploy --only functions
      
      - name: Deploy Firebase Hosting
        run: npx firebase deploy --only hosting
      
      - name: Run post-deployment checks
        run: npm run test:verification:dev
      
      - name: Notify deployment success
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_DEV }}
          slack-message: "🚀 Successfully deployed to Development environment! Check it out: https://db888-dev.web.app"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      
      - name: Notify deployment failure
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_DEV }}
          slack-message: "❌ Failed to deploy to Development environment! Please check the logs: https://github.com/voca9204@gmail.com/db2/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
